apiVersion: v1
kind: Service
metadata:
  name: profile-card-component
  namespace: default
spec:
  selector:
    app: profile-card-component-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
